[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1a1a1a"

[browser]
gatherUsageStats = false