# Groq SDK Configuration - Llama 3.1 8B Instant
LLM_BASE_URL = "https://api.groq.com"
GROQ_API_KEY = "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"
LLM_MODEL = "llama-3.1-8b-instant"
LLM_TEMPERATURE = "0.05"
LLM_TIMEOUT = "300"
MAX_RESPONSE_TOKENS = "1024"

SEARCH_LIMIT = "20"
RELEVANCE_THRESHOLD = "0.1"
MAX_CONTEXT_LENGTH = "4000"
CHUNK_OVERLAP_RANGE = "3"

BATCH_SIZE = "1000"
MAX_SCAN_LIMIT = "50000"
ENABLE_CACHING = "1"

MIN_CHUNK_RELEVANCE = "0.08"
MAX_BOOKS_PER_RESPONSE = "5"
ENABLE_HALLUCINATION_CHECK = "1"

CONVERSATION_HISTORY_LIMIT = "6"
HISTORY_CONTENT_LIMIT = "150"
